[package]
name = "searchy"
version = "0.5.0"
edition = "2021"

[[bin]]
name = "searchy"
path = "src/searchy.rs"

[[bin]]
name = "searchyd"
path = "src/daemon.rs"

[dependencies]
iced = "0.9"
fuzzy-matcher = "0.3.7"
once_cell = "1.17.1"
