[package]
name = "searchy"
version = "0.5.0"
edition = "2021"

[[bin]]
name = "searchy"
path = "src/searchy.rs"

[[bin]]
name = "searchyd"
path = "src/daemon.rs"

[dependencies]
druid = "0.8.3"
fuzzy-matcher = "0.3.7"
imgui = "0.10.0"
