[workspace]
resolver = "2"
members = [
    "actions",
    "ipc_communication",
    "searchy-client",
    "searchyd",
    "iced_keyboard_capture",
    "interface/scrolling",
    "interface/messages",
    "interface/searchbox",
]

