[package]
name = "searchy"
version = "0.5.0"
edition = "2021"

[[bin]]
name = "searchy"
path = "src/searchy.rs"

[[bin]]
name = "searchyd"
path = "src/daemon.rs"

[dependencies]
eframe = "0.21.3"
tantivy = "0.19.2"
