[package]
name = "javascript_repl_history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
iced_native = "0.10.3"
messages = { path = "../messages" }